-- 1. ENUMS
CREATE TYPE user_role AS ENUM ('syndic', 'adjoint', 'concierge', 'resident');

-- 2. PROFILES
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  role user_role NOT NULL DEFAULT 'resident',
  first_name TEXT,
  last_name TEXT,
  phone_number TEXT,
  floor INT,
  apartment_number INT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. INCIDENTS
CREATE TABLE incidents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  type TEXT NOT NULL, -- 'leak', 'electric', 'cleaning', 'staff_complaint', 'other'
  status TEXT DEFAULT 'open', -- 'open', 'in_progress', 'resolved'
  reporter_id UUID REFERENCES profiles(id),
  is_urgent BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TRANSACTIONS
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC NOT NULL,
  type TEXT NOT NULL, -- 'income', 'expense'
  category TEXT,
  description TEXT,
  date DATE NOT NULL,
  resident_id UUID REFERENCES profiles(id), -- Nullable if expense
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. BLOG POSTS
CREATE TABLE blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  image_url TEXT,
  author_id UUID REFERENCES profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TASKS (Syndic To-Do)
CREATE TABLE tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS POLICIES (Security)

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- PROFILES:
-- Public Read (for directory) - In real app, restrict to authenticated users
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
-- Update own profile
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- INCIDENTS:
-- Concierge: Cannot see 'staff_complaint'
CREATE POLICY "Concierge view limited" ON incidents FOR SELECT USING (
  (auth.uid() IN (SELECT id FROM profiles WHERE role = 'concierge')) AND type != 'staff_complaint'
);
-- Non-Concierge: See all
CREATE POLICY "Others view all" ON incidents FOR SELECT USING (
  auth.uid() NOT IN (SELECT id FROM profiles WHERE role = 'concierge')
);
-- Create: Everyone
CREATE POLICY "Everyone can create incidents" ON incidents FOR INSERT WITH CHECK (true);

-- TRANSACTIONS:
-- Concierge: NO ACCESS
CREATE POLICY "No access for concierge" ON transactions FOR SELECT USING (
  auth.uid() NOT IN (SELECT id FROM profiles WHERE role = 'concierge')
);
-- Syndic/Adjoint/Resident: View (Resident only own?)
-- For simplicity in this iteration: Syndic/Adjoint view all, Resident views own.
CREATE POLICY "Syndic Adjoint view all" ON transactions FOR SELECT USING (
  auth.uid() IN (SELECT id FROM profiles WHERE role IN ('syndic', 'adjoint'))
);
CREATE POLICY "Resident view own" ON transactions FOR SELECT USING (
  resident_id = auth.uid()
);

-- BLOG POSTS:
-- Concierge: NO ACCESS
CREATE POLICY "No blog for concierge" ON blog_posts FOR SELECT USING (
  auth.uid() NOT IN (SELECT id FROM profiles WHERE role = 'concierge')
);
-- Others: View all
CREATE POLICY "Others view blog" ON blog_posts FOR SELECT USING (
  auth.uid() NOT IN (SELECT id FROM profiles WHERE role = 'concierge')
);

-- TASKS:
-- Only Syndic/Adjoint/Concierge (Own tasks?) - For now, global task list for staff
CREATE POLICY "Staff view tasks" ON tasks FOR ALL USING (
  auth.uid() IN (SELECT id FROM profiles WHERE role IN ('syndic', 'adjoint', 'concierge'))
);
