-- AMANDIER SUITE V2.0 - SUPABASE SCHEMA
-- Optimized for "Manager" & "Life" Apps

-- 1. RESIDENT STATUS (Sync from Local DB)
CREATE TABLE IF NOT EXISTS public.resident_status (
    phone text NOT NULL PRIMARY KEY,
    balance double precision DEFAULT 0,
    last_updated timestamp with time zone DEFAULT now(),
    resident_name text,
    apt_number text,
    floor_number integer,
    pin_code text -- Used for Login in Amandier Life
);

-- 2. INCIDENTS (Reporting System)
CREATE TABLE IF NOT EXISTS public.incidents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    description text,
    is_anonymous boolean DEFAULT false,
    is_urgent boolean DEFAULT false, -- Triggers Siren in Admin App
    is_done boolean DEFAULT false,
    resident_phone text,
    apt_number text,
    assigned_provider_id integer
);

-- 3. APP CONFIG (Remote Config)
CREATE TABLE IF NOT EXISTS public.app_config (
    key text NOT NULL PRIMARY KEY,
    value text,
    description text
);

-- 4. SYNDIC POSTS (News Feed)
CREATE TABLE IF NOT EXISTS public.syndic_posts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    title text NOT NULL,
    content text,
    is_published boolean DEFAULT true
);

-- 5. BUILDING HEALTH (Dashboard Indicator)
CREATE TABLE IF NOT EXISTS public.building_health (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status text DEFAULT 'GREEN', -- 'GREEN', 'ORANGE', 'RED'
    last_updated timestamp with time zone DEFAULT now()
);

-- ROW LEVEL SECURITY (RLS) - SIMPLIFIED FOR V2
ALTER TABLE public.resident_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

-- Allow everything for now (Dev Mode/Low Friction)
-- In production, restrict based on Auth UID
CREATE POLICY "Enable read/write for all" ON public.resident_status FOR ALL USING (true);
CREATE POLICY "Enable read/write for all" ON public.incidents FOR ALL USING (true);
CREATE POLICY "Enable read for all" ON public.app_config FOR SELECT USING (true);
CREATE POLICY "Enable read for all" ON public.syndic_posts FOR SELECT USING (true);
CREATE POLICY "Enable read for all" ON public.building_health FOR SELECT USING (true);

-- SEED DATA (Optional)
INSERT INTO public.app_config (key, value, description) 
VALUES ('camera_url', 'https://via.placeholder.com/600x400.png?text=Camera+Entree+Live', 'URL du flux caméra entrée')
ON CONFLICT DO NOTHING;

INSERT INTO public.building_health (status) VALUES ('GREEN') ON CONFLICT DO NOTHING;
